name: Block_clock
version: '${version}'
main: org.minty.block_clock.Block_clock
#api-version: '1.18'
api-version: '1.20'
commands:
  clock:
    usage: clock x1 y1 z1 x2 y2 z2 clockName
    permission: clock.adding, clock.admin
    permission-message: "u have not permission"
  clock_settings:
    permission: clock.changing, clock.admin
    permission-message: "u have not permission"

